# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabe/zpr/proj/ZPR-Agario

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabe/zpr/proj/ZPR-Agario

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabe/zpr/proj/ZPR-Agario/CMakeFiles /home/gabe/zpr/proj/ZPR-Agario/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabe/zpr/proj/ZPR-Agario/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Agario

# Build rule for target.
Agario: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Agario
.PHONY : Agario

# fast build rule for target.
Agario/fast:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/build
.PHONY : Agario/fast

#=============================================================================
# Target rules for targets named AppTest

# Build rule for target.
AppTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppTest
.PHONY : AppTest

# fast build rule for target.
AppTest/fast:
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/build
.PHONY : AppTest/fast

src/controllers/AppController.o: src/controllers/AppController.cpp.o

.PHONY : src/controllers/AppController.o

# target to build an object file
src/controllers/AppController.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/AppController.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/AppController.cpp.o
.PHONY : src/controllers/AppController.cpp.o

src/controllers/AppController.i: src/controllers/AppController.cpp.i

.PHONY : src/controllers/AppController.i

# target to preprocess a source file
src/controllers/AppController.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/AppController.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/AppController.cpp.i
.PHONY : src/controllers/AppController.cpp.i

src/controllers/AppController.s: src/controllers/AppController.cpp.s

.PHONY : src/controllers/AppController.s

# target to generate assembly for a file
src/controllers/AppController.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/AppController.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/AppController.cpp.s
.PHONY : src/controllers/AppController.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/models/App.o: src/models/App.cpp.o

.PHONY : src/models/App.o

# target to build an object file
src/models/App.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/App.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/App.cpp.o
.PHONY : src/models/App.cpp.o

src/models/App.i: src/models/App.cpp.i

.PHONY : src/models/App.i

# target to preprocess a source file
src/models/App.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/App.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/App.cpp.i
.PHONY : src/models/App.cpp.i

src/models/App.s: src/models/App.cpp.s

.PHONY : src/models/App.s

# target to generate assembly for a file
src/models/App.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/App.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/App.cpp.s
.PHONY : src/models/App.cpp.s

src/models/StartModel.o: src/models/StartModel.cpp.o

.PHONY : src/models/StartModel.o

# target to build an object file
src/models/StartModel.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/StartModel.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/StartModel.cpp.o
.PHONY : src/models/StartModel.cpp.o

src/models/StartModel.i: src/models/StartModel.cpp.i

.PHONY : src/models/StartModel.i

# target to preprocess a source file
src/models/StartModel.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/StartModel.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/StartModel.cpp.i
.PHONY : src/models/StartModel.cpp.i

src/models/StartModel.s: src/models/StartModel.cpp.s

.PHONY : src/models/StartModel.s

# target to generate assembly for a file
src/models/StartModel.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/StartModel.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/StartModel.cpp.s
.PHONY : src/models/StartModel.cpp.s

src/models/StateModel.o: src/models/StateModel.cpp.o

.PHONY : src/models/StateModel.o

# target to build an object file
src/models/StateModel.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/StateModel.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/StateModel.cpp.o
.PHONY : src/models/StateModel.cpp.o

src/models/StateModel.i: src/models/StateModel.cpp.i

.PHONY : src/models/StateModel.i

# target to preprocess a source file
src/models/StateModel.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/StateModel.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/StateModel.cpp.i
.PHONY : src/models/StateModel.cpp.i

src/models/StateModel.s: src/models/StateModel.cpp.s

.PHONY : src/models/StateModel.s

# target to generate assembly for a file
src/models/StateModel.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/StateModel.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/StateModel.cpp.s
.PHONY : src/models/StateModel.cpp.s

src/views/AppView.o: src/views/AppView.cpp.o

.PHONY : src/views/AppView.o

# target to build an object file
src/views/AppView.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/AppView.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/AppView.cpp.o
.PHONY : src/views/AppView.cpp.o

src/views/AppView.i: src/views/AppView.cpp.i

.PHONY : src/views/AppView.i

# target to preprocess a source file
src/views/AppView.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/AppView.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/AppView.cpp.i
.PHONY : src/views/AppView.cpp.i

src/views/AppView.s: src/views/AppView.cpp.s

.PHONY : src/views/AppView.s

# target to generate assembly for a file
src/views/AppView.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/AppView.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/AppView.cpp.s
.PHONY : src/views/AppView.cpp.s

src/views/EndView.o: src/views/EndView.cpp.o

.PHONY : src/views/EndView.o

# target to build an object file
src/views/EndView.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/EndView.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/EndView.cpp.o
.PHONY : src/views/EndView.cpp.o

src/views/EndView.i: src/views/EndView.cpp.i

.PHONY : src/views/EndView.i

# target to preprocess a source file
src/views/EndView.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/EndView.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/EndView.cpp.i
.PHONY : src/views/EndView.cpp.i

src/views/EndView.s: src/views/EndView.cpp.s

.PHONY : src/views/EndView.s

# target to generate assembly for a file
src/views/EndView.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/EndView.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/EndView.cpp.s
.PHONY : src/views/EndView.cpp.s

src/views/StartView.o: src/views/StartView.cpp.o

.PHONY : src/views/StartView.o

# target to build an object file
src/views/StartView.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/StartView.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/StartView.cpp.o
.PHONY : src/views/StartView.cpp.o

src/views/StartView.i: src/views/StartView.cpp.i

.PHONY : src/views/StartView.i

# target to preprocess a source file
src/views/StartView.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/StartView.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/StartView.cpp.i
.PHONY : src/views/StartView.cpp.i

src/views/StartView.s: src/views/StartView.cpp.s

.PHONY : src/views/StartView.s

# target to generate assembly for a file
src/views/StartView.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/StartView.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/StartView.cpp.s
.PHONY : src/views/StartView.cpp.s

tests/models/AppTest.o: tests/models/AppTest.cpp.o

.PHONY : tests/models/AppTest.o

# target to build an object file
tests/models/AppTest.cpp.o:
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/tests/models/AppTest.cpp.o
.PHONY : tests/models/AppTest.cpp.o

tests/models/AppTest.i: tests/models/AppTest.cpp.i

.PHONY : tests/models/AppTest.i

# target to preprocess a source file
tests/models/AppTest.cpp.i:
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/tests/models/AppTest.cpp.i
.PHONY : tests/models/AppTest.cpp.i

tests/models/AppTest.s: tests/models/AppTest.cpp.s

.PHONY : tests/models/AppTest.s

# target to generate assembly for a file
tests/models/AppTest.cpp.s:
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/tests/models/AppTest.cpp.s
.PHONY : tests/models/AppTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... Agario"
	@echo "... AppTest"
	@echo "... src/controllers/AppController.o"
	@echo "... src/controllers/AppController.i"
	@echo "... src/controllers/AppController.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/models/App.o"
	@echo "... src/models/App.i"
	@echo "... src/models/App.s"
	@echo "... src/models/StartModel.o"
	@echo "... src/models/StartModel.i"
	@echo "... src/models/StartModel.s"
	@echo "... src/models/StateModel.o"
	@echo "... src/models/StateModel.i"
	@echo "... src/models/StateModel.s"
	@echo "... src/views/AppView.o"
	@echo "... src/views/AppView.i"
	@echo "... src/views/AppView.s"
	@echo "... src/views/EndView.o"
	@echo "... src/views/EndView.i"
	@echo "... src/views/EndView.s"
	@echo "... src/views/StartView.o"
	@echo "... src/views/StartView.i"
	@echo "... src/views/StartView.s"
	@echo "... tests/models/AppTest.o"
	@echo "... tests/models/AppTest.i"
	@echo "... tests/models/AppTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

