# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabe/zpr/proj/ZPR-Agario

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabe/zpr/proj/ZPR-Agario

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabe/zpr/proj/ZPR-Agario/CMakeFiles /home/gabe/zpr/proj/ZPR-Agario/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabe/zpr/proj/ZPR-Agario/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Agario

# Build rule for target.
Agario: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Agario
.PHONY : Agario

# fast build rule for target.
Agario/fast:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/build
.PHONY : Agario/fast

#=============================================================================
# Target rules for targets named AppTest

# Build rule for target.
AppTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppTest
.PHONY : AppTest

# fast build rule for target.
AppTest/fast:
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/build
.PHONY : AppTest/fast

src/controllers/AppController.o: src/controllers/AppController.cpp.o

.PHONY : src/controllers/AppController.o

# target to build an object file
src/controllers/AppController.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/AppController.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/AppController.cpp.o
.PHONY : src/controllers/AppController.cpp.o

src/controllers/AppController.i: src/controllers/AppController.cpp.i

.PHONY : src/controllers/AppController.i

# target to preprocess a source file
src/controllers/AppController.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/AppController.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/AppController.cpp.i
.PHONY : src/controllers/AppController.cpp.i

src/controllers/AppController.s: src/controllers/AppController.cpp.s

.PHONY : src/controllers/AppController.s

# target to generate assembly for a file
src/controllers/AppController.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/AppController.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/AppController.cpp.s
.PHONY : src/controllers/AppController.cpp.s

src/controllers/states/EndController.o: src/controllers/states/EndController.cpp.o

.PHONY : src/controllers/states/EndController.o

# target to build an object file
src/controllers/states/EndController.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/EndController.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/EndController.cpp.o
.PHONY : src/controllers/states/EndController.cpp.o

src/controllers/states/EndController.i: src/controllers/states/EndController.cpp.i

.PHONY : src/controllers/states/EndController.i

# target to preprocess a source file
src/controllers/states/EndController.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/EndController.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/EndController.cpp.i
.PHONY : src/controllers/states/EndController.cpp.i

src/controllers/states/EndController.s: src/controllers/states/EndController.cpp.s

.PHONY : src/controllers/states/EndController.s

# target to generate assembly for a file
src/controllers/states/EndController.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/EndController.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/EndController.cpp.s
.PHONY : src/controllers/states/EndController.cpp.s

src/controllers/states/PauseController.o: src/controllers/states/PauseController.cpp.o

.PHONY : src/controllers/states/PauseController.o

# target to build an object file
src/controllers/states/PauseController.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/PauseController.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/PauseController.cpp.o
.PHONY : src/controllers/states/PauseController.cpp.o

src/controllers/states/PauseController.i: src/controllers/states/PauseController.cpp.i

.PHONY : src/controllers/states/PauseController.i

# target to preprocess a source file
src/controllers/states/PauseController.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/PauseController.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/PauseController.cpp.i
.PHONY : src/controllers/states/PauseController.cpp.i

src/controllers/states/PauseController.s: src/controllers/states/PauseController.cpp.s

.PHONY : src/controllers/states/PauseController.s

# target to generate assembly for a file
src/controllers/states/PauseController.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/PauseController.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/PauseController.cpp.s
.PHONY : src/controllers/states/PauseController.cpp.s

src/controllers/states/PlayController.o: src/controllers/states/PlayController.cpp.o

.PHONY : src/controllers/states/PlayController.o

# target to build an object file
src/controllers/states/PlayController.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/PlayController.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/PlayController.cpp.o
.PHONY : src/controllers/states/PlayController.cpp.o

src/controllers/states/PlayController.i: src/controllers/states/PlayController.cpp.i

.PHONY : src/controllers/states/PlayController.i

# target to preprocess a source file
src/controllers/states/PlayController.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/PlayController.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/PlayController.cpp.i
.PHONY : src/controllers/states/PlayController.cpp.i

src/controllers/states/PlayController.s: src/controllers/states/PlayController.cpp.s

.PHONY : src/controllers/states/PlayController.s

# target to generate assembly for a file
src/controllers/states/PlayController.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/PlayController.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/PlayController.cpp.s
.PHONY : src/controllers/states/PlayController.cpp.s

src/controllers/states/StartController.o: src/controllers/states/StartController.cpp.o

.PHONY : src/controllers/states/StartController.o

# target to build an object file
src/controllers/states/StartController.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/StartController.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/StartController.cpp.o
.PHONY : src/controllers/states/StartController.cpp.o

src/controllers/states/StartController.i: src/controllers/states/StartController.cpp.i

.PHONY : src/controllers/states/StartController.i

# target to preprocess a source file
src/controllers/states/StartController.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/StartController.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/StartController.cpp.i
.PHONY : src/controllers/states/StartController.cpp.i

src/controllers/states/StartController.s: src/controllers/states/StartController.cpp.s

.PHONY : src/controllers/states/StartController.s

# target to generate assembly for a file
src/controllers/states/StartController.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/controllers/states/StartController.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/controllers/states/StartController.cpp.s
.PHONY : src/controllers/states/StartController.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/models/App.o: src/models/App.cpp.o

.PHONY : src/models/App.o

# target to build an object file
src/models/App.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/App.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/App.cpp.o
.PHONY : src/models/App.cpp.o

src/models/App.i: src/models/App.cpp.i

.PHONY : src/models/App.i

# target to preprocess a source file
src/models/App.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/App.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/App.cpp.i
.PHONY : src/models/App.cpp.i

src/models/App.s: src/models/App.cpp.s

.PHONY : src/models/App.s

# target to generate assembly for a file
src/models/App.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/App.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/App.cpp.s
.PHONY : src/models/App.cpp.s

src/models/states/EndModel.o: src/models/states/EndModel.cpp.o

.PHONY : src/models/states/EndModel.o

# target to build an object file
src/models/states/EndModel.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/EndModel.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/EndModel.cpp.o
.PHONY : src/models/states/EndModel.cpp.o

src/models/states/EndModel.i: src/models/states/EndModel.cpp.i

.PHONY : src/models/states/EndModel.i

# target to preprocess a source file
src/models/states/EndModel.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/EndModel.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/EndModel.cpp.i
.PHONY : src/models/states/EndModel.cpp.i

src/models/states/EndModel.s: src/models/states/EndModel.cpp.s

.PHONY : src/models/states/EndModel.s

# target to generate assembly for a file
src/models/states/EndModel.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/EndModel.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/EndModel.cpp.s
.PHONY : src/models/states/EndModel.cpp.s

src/models/states/PauseModel.o: src/models/states/PauseModel.cpp.o

.PHONY : src/models/states/PauseModel.o

# target to build an object file
src/models/states/PauseModel.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/PauseModel.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/PauseModel.cpp.o
.PHONY : src/models/states/PauseModel.cpp.o

src/models/states/PauseModel.i: src/models/states/PauseModel.cpp.i

.PHONY : src/models/states/PauseModel.i

# target to preprocess a source file
src/models/states/PauseModel.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/PauseModel.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/PauseModel.cpp.i
.PHONY : src/models/states/PauseModel.cpp.i

src/models/states/PauseModel.s: src/models/states/PauseModel.cpp.s

.PHONY : src/models/states/PauseModel.s

# target to generate assembly for a file
src/models/states/PauseModel.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/PauseModel.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/PauseModel.cpp.s
.PHONY : src/models/states/PauseModel.cpp.s

src/models/states/PlayModel.o: src/models/states/PlayModel.cpp.o

.PHONY : src/models/states/PlayModel.o

# target to build an object file
src/models/states/PlayModel.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/PlayModel.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/PlayModel.cpp.o
.PHONY : src/models/states/PlayModel.cpp.o

src/models/states/PlayModel.i: src/models/states/PlayModel.cpp.i

.PHONY : src/models/states/PlayModel.i

# target to preprocess a source file
src/models/states/PlayModel.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/PlayModel.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/PlayModel.cpp.i
.PHONY : src/models/states/PlayModel.cpp.i

src/models/states/PlayModel.s: src/models/states/PlayModel.cpp.s

.PHONY : src/models/states/PlayModel.s

# target to generate assembly for a file
src/models/states/PlayModel.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/PlayModel.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/PlayModel.cpp.s
.PHONY : src/models/states/PlayModel.cpp.s

src/models/states/StartModel.o: src/models/states/StartModel.cpp.o

.PHONY : src/models/states/StartModel.o

# target to build an object file
src/models/states/StartModel.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/StartModel.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/StartModel.cpp.o
.PHONY : src/models/states/StartModel.cpp.o

src/models/states/StartModel.i: src/models/states/StartModel.cpp.i

.PHONY : src/models/states/StartModel.i

# target to preprocess a source file
src/models/states/StartModel.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/StartModel.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/StartModel.cpp.i
.PHONY : src/models/states/StartModel.cpp.i

src/models/states/StartModel.s: src/models/states/StartModel.cpp.s

.PHONY : src/models/states/StartModel.s

# target to generate assembly for a file
src/models/states/StartModel.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/models/states/StartModel.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/models/states/StartModel.cpp.s
.PHONY : src/models/states/StartModel.cpp.s

src/views/AppView.o: src/views/AppView.cpp.o

.PHONY : src/views/AppView.o

# target to build an object file
src/views/AppView.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/AppView.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/AppView.cpp.o
.PHONY : src/views/AppView.cpp.o

src/views/AppView.i: src/views/AppView.cpp.i

.PHONY : src/views/AppView.i

# target to preprocess a source file
src/views/AppView.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/AppView.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/AppView.cpp.i
.PHONY : src/views/AppView.cpp.i

src/views/AppView.s: src/views/AppView.cpp.s

.PHONY : src/views/AppView.s

# target to generate assembly for a file
src/views/AppView.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/AppView.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/AppView.cpp.s
.PHONY : src/views/AppView.cpp.s

src/views/states/EndView.o: src/views/states/EndView.cpp.o

.PHONY : src/views/states/EndView.o

# target to build an object file
src/views/states/EndView.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/EndView.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/EndView.cpp.o
.PHONY : src/views/states/EndView.cpp.o

src/views/states/EndView.i: src/views/states/EndView.cpp.i

.PHONY : src/views/states/EndView.i

# target to preprocess a source file
src/views/states/EndView.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/EndView.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/EndView.cpp.i
.PHONY : src/views/states/EndView.cpp.i

src/views/states/EndView.s: src/views/states/EndView.cpp.s

.PHONY : src/views/states/EndView.s

# target to generate assembly for a file
src/views/states/EndView.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/EndView.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/EndView.cpp.s
.PHONY : src/views/states/EndView.cpp.s

src/views/states/PauseView.o: src/views/states/PauseView.cpp.o

.PHONY : src/views/states/PauseView.o

# target to build an object file
src/views/states/PauseView.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/PauseView.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/PauseView.cpp.o
.PHONY : src/views/states/PauseView.cpp.o

src/views/states/PauseView.i: src/views/states/PauseView.cpp.i

.PHONY : src/views/states/PauseView.i

# target to preprocess a source file
src/views/states/PauseView.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/PauseView.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/PauseView.cpp.i
.PHONY : src/views/states/PauseView.cpp.i

src/views/states/PauseView.s: src/views/states/PauseView.cpp.s

.PHONY : src/views/states/PauseView.s

# target to generate assembly for a file
src/views/states/PauseView.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/PauseView.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/PauseView.cpp.s
.PHONY : src/views/states/PauseView.cpp.s

src/views/states/PlayView.o: src/views/states/PlayView.cpp.o

.PHONY : src/views/states/PlayView.o

# target to build an object file
src/views/states/PlayView.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/PlayView.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/PlayView.cpp.o
.PHONY : src/views/states/PlayView.cpp.o

src/views/states/PlayView.i: src/views/states/PlayView.cpp.i

.PHONY : src/views/states/PlayView.i

# target to preprocess a source file
src/views/states/PlayView.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/PlayView.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/PlayView.cpp.i
.PHONY : src/views/states/PlayView.cpp.i

src/views/states/PlayView.s: src/views/states/PlayView.cpp.s

.PHONY : src/views/states/PlayView.s

# target to generate assembly for a file
src/views/states/PlayView.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/PlayView.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/PlayView.cpp.s
.PHONY : src/views/states/PlayView.cpp.s

src/views/states/StartView.o: src/views/states/StartView.cpp.o

.PHONY : src/views/states/StartView.o

# target to build an object file
src/views/states/StartView.cpp.o:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/StartView.cpp.o
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/StartView.cpp.o
.PHONY : src/views/states/StartView.cpp.o

src/views/states/StartView.i: src/views/states/StartView.cpp.i

.PHONY : src/views/states/StartView.i

# target to preprocess a source file
src/views/states/StartView.cpp.i:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/StartView.cpp.i
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/StartView.cpp.i
.PHONY : src/views/states/StartView.cpp.i

src/views/states/StartView.s: src/views/states/StartView.cpp.s

.PHONY : src/views/states/StartView.s

# target to generate assembly for a file
src/views/states/StartView.cpp.s:
	$(MAKE) -f CMakeFiles/Agario.dir/build.make CMakeFiles/Agario.dir/src/views/states/StartView.cpp.s
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/src/views/states/StartView.cpp.s
.PHONY : src/views/states/StartView.cpp.s

tests/models/AppTest.o: tests/models/AppTest.cpp.o

.PHONY : tests/models/AppTest.o

# target to build an object file
tests/models/AppTest.cpp.o:
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/tests/models/AppTest.cpp.o
.PHONY : tests/models/AppTest.cpp.o

tests/models/AppTest.i: tests/models/AppTest.cpp.i

.PHONY : tests/models/AppTest.i

# target to preprocess a source file
tests/models/AppTest.cpp.i:
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/tests/models/AppTest.cpp.i
.PHONY : tests/models/AppTest.cpp.i

tests/models/AppTest.s: tests/models/AppTest.cpp.s

.PHONY : tests/models/AppTest.s

# target to generate assembly for a file
tests/models/AppTest.cpp.s:
	$(MAKE) -f CMakeFiles/AppTest.dir/build.make CMakeFiles/AppTest.dir/tests/models/AppTest.cpp.s
.PHONY : tests/models/AppTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... Agario"
	@echo "... AppTest"
	@echo "... src/controllers/AppController.o"
	@echo "... src/controllers/AppController.i"
	@echo "... src/controllers/AppController.s"
	@echo "... src/controllers/states/EndController.o"
	@echo "... src/controllers/states/EndController.i"
	@echo "... src/controllers/states/EndController.s"
	@echo "... src/controllers/states/PauseController.o"
	@echo "... src/controllers/states/PauseController.i"
	@echo "... src/controllers/states/PauseController.s"
	@echo "... src/controllers/states/PlayController.o"
	@echo "... src/controllers/states/PlayController.i"
	@echo "... src/controllers/states/PlayController.s"
	@echo "... src/controllers/states/StartController.o"
	@echo "... src/controllers/states/StartController.i"
	@echo "... src/controllers/states/StartController.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/models/App.o"
	@echo "... src/models/App.i"
	@echo "... src/models/App.s"
	@echo "... src/models/states/EndModel.o"
	@echo "... src/models/states/EndModel.i"
	@echo "... src/models/states/EndModel.s"
	@echo "... src/models/states/PauseModel.o"
	@echo "... src/models/states/PauseModel.i"
	@echo "... src/models/states/PauseModel.s"
	@echo "... src/models/states/PlayModel.o"
	@echo "... src/models/states/PlayModel.i"
	@echo "... src/models/states/PlayModel.s"
	@echo "... src/models/states/StartModel.o"
	@echo "... src/models/states/StartModel.i"
	@echo "... src/models/states/StartModel.s"
	@echo "... src/views/AppView.o"
	@echo "... src/views/AppView.i"
	@echo "... src/views/AppView.s"
	@echo "... src/views/states/EndView.o"
	@echo "... src/views/states/EndView.i"
	@echo "... src/views/states/EndView.s"
	@echo "... src/views/states/PauseView.o"
	@echo "... src/views/states/PauseView.i"
	@echo "... src/views/states/PauseView.s"
	@echo "... src/views/states/PlayView.o"
	@echo "... src/views/states/PlayView.i"
	@echo "... src/views/states/PlayView.s"
	@echo "... src/views/states/StartView.o"
	@echo "... src/views/states/StartView.i"
	@echo "... src/views/states/StartView.s"
	@echo "... tests/models/AppTest.o"
	@echo "... tests/models/AppTest.i"
	@echo "... tests/models/AppTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

